sudo: false
language: node_js
node_js:
  - "0.10"
env:
  - TEST_DIR=/
  - TEST_DIR=packages/dispatchr
  - TEST_DIR=packages/fluxible
  - TEST_DIR=packages/fluxible-plugin-fetchr
  - TEST_DIR=packages/fluxible-reducer-store
  - TEST_DIR=packages/fluxible-addons-react
  - TEST_DIR=packages/fluxible-router
  - TEST_DIR=packages/generator-fluxible
  - TEST_DIR=site
script: cd $TEST_DIR && npm test
after_success:
  - "npm run cover"
  - "cat artifacts/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
