sudo: false
language: node_js
matrix:
  allow_failures:
    - node_js: "iojs"
node_js:
  - "iojs"
  - "0.12"
  - "0.10"
env:
  - TEST_DIR=packages/fluxible
  - TEST_DIR=packages/fluxible-reducer-store
  - TEST_DIR=packages/fluxible-addons-react
  - TEST_DIR=packages/generator-fluxible
script: cd $TEST_DIR && npm test
after_success:
  - "npm run cover"
  - "cat artifacts/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
